/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.Business.AnioBusiness;
import Code.Business.AuxiliaresBusiness;
import Code.Business.InstitucionEducativaBusiness;
import Code.Business.SedeBusiness;
import Code.Domain.Anio;
import Code.Domain.InstitucionEducativa;
import Code.Domain.Sede;
import GUI.Util.ControllerComboAnio;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author laynegranadosmogollon
 */
public class AnioModal extends javax.swing.JDialog {
    
    private boolean ALLOW_ROW_SELECTION = true;
    
    ControllerComboAnio controller;
    AnioBusiness anioBusiness;    
    InstitucionEducativaBusiness institucionEducativaBusiness;
    AuxiliaresBusiness auxiliaresBusiness;    
    Anio anioActual;
    InstitucionEducativa actualColegio;
    ArrayList<Anio> anios;
    SedeBusiness sedeBusiness;
    
    
    final String[] columnNames = {"Id", "Año","Descripcion", "Sede Id", "Sede"};

    /**
     * Creates new form AnioModal
     */
    public AnioModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.institucionEducativaBusiness= new InstitucionEducativaBusiness();
        this.actualColegio = this.institucionEducativaBusiness.selectColegio();

        this.controller= new ControllerComboAnio(this);
        this.auxiliaresBusiness = new AuxiliaresBusiness();
        this.anioBusiness = new AnioBusiness();
        this.anios = this.anioBusiness.selectAllAnios();
        
        this.anioActual = new Anio();
        
        JTable jtable = this.createJTable(this.dataTable());
        this.scrollListadoAnios.setViewportView(jtable);
        this.sedeBusiness = new SedeBusiness();
    }

    public InstitucionEducativa getActualColegio() {
        return actualColegio;
    }

    public void setActualColegio(InstitucionEducativa actualColegio) {
        this.actualColegio = actualColegio;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumAnio = new javax.swing.JTextField();
        cmbSedeAnio = new GUI.Util.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        btnGuardarAnio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionAnio = new javax.swing.JTextArea();
        btnLimpiarCampos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scrollListadoAnios = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        lblIdAnio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Agregar o Modificar nuevo año a Sede");

        jLabel7.setText("Año (Solo números)");

        txtNumAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAnioActionPerformed(evt);
            }
        });

        cmbSedeAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSedeAnioActionPerformed(evt);
            }
        });

        jLabel10.setText("Sede");

        btnGuardarAnio.setText("Guardar Año");
        btnGuardarAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAnioActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripción");

        txtDescripcionAnio.setColumns(20);
        txtDescripcionAnio.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionAnio);

        btnLimpiarCampos.setText("Nuevo año");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel2.setText("(Opcional)");

        jLabel3.setText("ID");

        lblIdAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIdAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbSedeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(290, 290, 290)
                                                .addComponent(scrollListadoAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(btnLimpiarCampos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGuardarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNumAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmbSedeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(lblIdAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarAnio)
                    .addComponent(btnLimpiarCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollListadoAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAnioActionPerformed

    private void cmbSedeAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSedeAnioActionPerformed

    }//GEN-LAST:event_cmbSedeAnioActionPerformed

    private void btnGuardarAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAnioActionPerformed
        
        Object sede = this.controller.getObjetoSeleccionado((GUI.Util.JComboBox)this.cmbSedeAnio);
        this.anioActual.setSede((Sede)sede);
        this.anioActual.setAnio(Integer.parseInt(this.txtNumAnio.getText()));
        this.anioActual.setDescripcion(String.valueOf(this.txtDescripcionAnio.getText()));
        
        if(this.anioActual.getId()>0){
            this.anioActual = this.anioBusiness.updateAnio(anioActual);
            for(int i=0;i<this.anios.size();i++){
                Anio anio = this.anios.get(i);
                if(anio.getId()==this.anioActual.getId()){
                    this.anios.set(i, this.anioActual);
                }
            }
        }else{
            this.anioActual = this.anioBusiness.guardarAnio(this.anioActual);
            this.anios.add(this.anioActual); 
        }
        
        
        this.scrollListadoAnios.setViewportView(null);
        
        JTable jTable2 = this.createJTable(this.dataTable());
        
        this.scrollListadoAnios.setViewportView(jTable2);
    }//GEN-LAST:event_btnGuardarAnioActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
        
        this.controller= new ControllerComboAnio(this);
        this.anioActual = new Anio();
        this.txtDescripcionAnio.setText("");
        this.txtNumAnio.setText("");
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnioModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnioModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnioModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnioModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnioModal dialog = new AnioModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAnio;
    private javax.swing.JButton btnLimpiarCampos;
    public javax.swing.JComboBox cmbSedeAnio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdAnio;
    private javax.swing.JScrollPane scrollListadoAnios;
    private javax.swing.JTextArea txtDescripcionAnio;
    private javax.swing.JTextField txtNumAnio;
    // End of variables declaration//GEN-END:variables
    
    private Object[][] dataTable(){
        int tamAnio = this.anios.size();
        Object[][] data = new Object[tamAnio][5];
        
        for(int i=0;i<anios.size();i++){
           Anio a = anios.get(i);
            data[i][0]= a.getId();
            data[i][1]= a.getAnio();
            data[i][2] =a.getDescripcion();
            data[i][3] = a.getSede().getId();
            data[i][4]= a.getSede().getNombre();

        }
        return data;
    }
    
    private JTable createJTable(Object[][] data){
        JTable jTable = new JTable(data, columnNames);
        jTable.setPreferredScrollableViewportSize(new Dimension(500, 70));
        jTable.setFillsViewportHeight(true);
        jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        if (ALLOW_ROW_SELECTION) {
            ListSelectionModel rowSM = jTable.getSelectionModel();
            rowSM.addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                    
                    if (e.getValueIsAdjusting()) 
                        return;

                    ListSelectionModel lsm = (ListSelectionModel)e.getSource();
                    if (!lsm.isSelectionEmpty()) {
                        getAnioSelected(jTable, lsm.getMinSelectionIndex());
                    }
                }
            });
        } else {
            jTable.setRowSelectionAllowed(false);
        }        
        return jTable;
    }
    private void getAnioSelected(JTable table, int row) {
        int numRows = table.getRowCount();

        if(row<numRows){
            javax.swing.table.TableModel model = table.getModel();
            this.anioActual= new Anio();
            this.anioActual.setId((Integer)(model.getValueAt(row,0)));
            this.anioActual.setAnio((Integer)(model.getValueAt(row,1)));
            this.anioActual.setDescripcion((String)(model.getValueAt(row, 2)));
            Sede sede = new Sede();
            sede.setId((Integer)model.getValueAt(row,3));
            sede.setNombre((String)model.getValueAt(row,4));
            this.anioActual.setSede(sede);
            this.lblIdAnio.setText(""+this.anioActual.getId());
            this.txtNumAnio.setText(String.valueOf(this.anioActual.getAnio()));
            this.txtDescripcionAnio.setText(String.valueOf(this.anioActual.getDescripcion()));
            //this.controller= new ControllerComboAnio(this);
            this.controller.setSelectedItemSede(sede);            
        }        
    }
}
